spring:
  application:
    name: bulletin-board

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bulletin
    username: movieapp
    password: 'movieapp'
    pool-size: 10
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
    flyway:
      enabled: true
      baselineOnMigrate: true
      validateOnMigrate: true
      locations: classpath:db/migration
  devtools:
    restart:
      exclude: static/**,public/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false


server:
  port: 9990
logging:
  level:
    root: INFO
mybatis:
  type-aliases-package: com.bulleting.bulletinboard.model
  mapper-locations: classpath:mapper/*.xml
